### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by ghost** [dimitrismistriotis/git-helpers#1]
Nevermind and happy fishing:)

**Comment by dimitrismistriotis** [comment]
Hi. I do not know if I answered to you I remember writing something in an email, probably did not send it or something.

My take:

I heard about fisherman when I bought my new laptop and I could not fork omf (it was blocked from github). From my perspective omf has everything I need, chruby, virtualenv, one theme. A reason that I might upgrade is the loading time, but whenever I switch on my machine, I open 2/3 terminals and work with them. So porting for speed is not that much of a bonus.

Generally the omf situation is "good enough" and the whole switching to fish shell experience brings up so many benefits that chasing after another optimization does not seem to yield that much benefit. :-(
